name: Environment Variables Validate
description: Validate environment variables against Dockerfile and env_vars.tf

inputs:
  dockerfile_path:
    description: 'Path to the Dockerfile'
    required: true
  terraform_dir:
    description: 'Path to the Terraform directory'
    required: true

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
    with:
      repository: 'boldlink/support-scripts'
      ref: 'main'
      path: 'support-scripts'

  - uses: actions/setup-python@v4
    with:
      python-version: '3.11'
      
  - name: Validate variables
    shell: "bash"
    run: python $GITHUB_WORKSPACE/support-scripts/scripts/github_actions/dockerfile_variables_validate/variables_validate.py ${{inputs.dockerfile_path}} ${{inputs.terraform_dir}}

